.\" Manpage para huayra-about
.\" Contact bolichep@gmail.com
.TH huayra-about 1 "16 Mar 2015" "0.1" "huayra-about man page"
.SH NOMBRE
huayra-about \- Acerca de Huayra 
.SH SINOPSIS
huayra-about [-h|--help] [-g|--gui] [-t|--tty]
.SH DESCRIPCION
huayra-about lista información referida a las versiones de la instalación de Huayra, Debian y el Kernel. Esta información se presenta en una ventana y/o en la consola.
.SH OPCIONES
.br
-h, --help
.br
	Muestra este mensaje de ayuda y termina.
.br
-g, --gui
.br
	Muestra una ventana con la información de versión de huayra.
.br
-t, --tty
.br
	Muestra la información de versión de huayra en la terminal.
.br
.SH AUTOR
huayra-about fue escrito por Pedro Boliche (bolichep@gmail.com). Web page: https://github.com/bolichep/huayra-about
.SH COPYRIGHT 
You can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
.br
This program is distributed in the hope that it will be useful,but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
.br
You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.


